name: Run Bash Script on Remote Server

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: VServer-2
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install SSH Pass
      run: sudo apt-get install sshpass

    - name: Run script on remote server
      run: sshpass -p ${{ secrets.PASSWORD }} ssh -o StrictHostKeyChecking=no ${{ secrets.USERNAME }}@${{ secrets.HOST }} 'bash -s' < /var/www/scripts/UpdateAPI.sh
