name: Node.js CI/CD

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Execute remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VLR_API_HOST }}
        username: ${{ secrets.VLR_API_USERNAME }}
        password: ${{ secrets.VLR_API_PASSWORD }}
        script: |
          cd ~/projects/vlr_api
          git pull
          npm install
          pm2 reload ecosystem.config.js
