name: Deploy to remote server

on:
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Copy file via scp
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.VLR_API_HOST }}
        username: ${{ secrets.VLR_API_USERNAME }}
        key: ${{ secrets.VLR_API_KEY }}
        source: "."
        target: "~/vlr.techeron.com"

    - name: Execute remote ssh commands
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VLR_API_HOST }}
        username: ${{ secrets.VLR_API_USERNAME }}
        key: ${{ secrets.VLR_API_KEY }}
        script: "cd ~/vlr.techeron.com && ./deploy-script.sh"
